FROM node:20 AS builder 

WORKDIR /app

ARG CLERK_SECRET_KEY
ARG NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_SUPABASE_URL

ENV CLERK_SECRET_KEY=$CLERK_SECRET_KEY
ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL

COPY ./package*.json . 

RUN npm ci

COPY . . 

RUN npm run build 

FROM node:20-alpine

WORKDIR /app 

ENV NODE_ENV=production 

COPY --from=builder /app .

RUN npm ci --omit=dev

EXPOSE 3000

CMD ["npm", "start"]
